### ISSUE TITLE
Practica 5

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo_eaaj#1]
[PRACTICA_5.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo_eaaj/files/14653959/PRACTICA_5.pdf)

**Comment by AricelCastro** [comment]
Calificación 20/20
Tienen todos lo criterios requeridos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
